# Generated by Django 4.2.13 on 2025-06-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_subscription_stripe_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('expired', 'Expired')], default='free', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('half_yearly', 'Half Yearly')], default='monthly', max_length=50),
        ),
    ]
