# Generated by Django 4.2.13 on 2025-06-30 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_subscription_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='duration_days',
        ),
    ]
